In [ ]:
import numpy as np
arr=np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
a=np.full((3,3),7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
b=np.arange(3,30,3)
print(b)

[ 3  6  9 12 15 18 21 24 27]


In [ ]:
print(np.random.random((2,2)))

[[0.48376399 0.99229122]
 [0.32521742 0.34907817]]


In [ ]:
narr=arr.reshape(3,2)
print(narr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
z=np.zeros((3,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
fz=z.flatten()
print(fz)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.shape)

(3, 3)


In [ ]:
print(a.size)

9


In [ ]:
print(a.dtype)

int64


In [ ]:
a1=a.astype("f")
print(a1)

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [ ]:
arr1=np.array([(1,3,5,6),(3,2,6,7),(9,8,4,7)])
print(arr1)

[[1 3 5 6]
 [3 2 6 7]
 [9 8 4 7]]


In [ ]:
print(arr1[0:3:2])

[[1 3 5 6]
 [9 8 4 7]]


In [ ]:
print(arr1[0::2])

[[1 3 5 6]
 [9 8 4 7]]


In [ ]:
print(arr1[::])

[[1 3 5 6]
 [3 2 6 7]
 [9 8 4 7]]


In [ ]:
print(arr1[0,1:3])

[3 5]


In [ ]:
print(arr1[2:,2])

[4]


In [ ]:
print(arr1[:,2])

[5 6 4]


In [ ]:
print(np.where(arr1==4))

(array([2]), array([2]))


In [ ]:
print(np.where(arr1%2!=0))

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 3, 0, 3]))


In [ ]:
print(np.where(arr1%2==0))

(array([0, 1, 1, 2, 2]), array([3, 1, 2, 1, 2]))


In [ ]:
print(np.sort(arr1))

[[1 3 5 6]
 [2 3 6 7]
 [4 7 8 9]]


In [ ]:
c=np.array([11,9,7,22])
x=[True,False,True,False]
nc=c>10
newc=c[nc]
print(c)
print(x)
print(nc)
print(newc)

[11  9  7 22]
[True, False, True, False]
[ True False False  True]
[11 22]


In [ ]:
y=np.array([3,8,5,4])
w=np.array([6,1,10,7])
print("y+w=",y+w)
print("y-w=",y-w)
print("y/w=",y/w)
print("y.dot(w)",y.dot(w))

y+w= [ 9  9 15 11]
y-w= [-3  7 -5 -3]
y/w= [0.5        8.         0.5        0.57142857]
y.dot(w) 104


In [ ]:
print(y*3)

[ 9 24 15 12]


In [ ]:
a1=[1,2,3,4]
a2=[5,6,7,8]
def vectorize_my_func(s,t):
  if(s>t):
    return(s-t)
  else:
    return(s+t)
vec_func=vectorize_my_func(a1,a2)
print(vec_func)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
x1=np.array([3,6,9,8])
y1=np.array([4,1,7,5])
print(np.concatenate((x1,y1)))

[3 6 9 8 4 1 7 5]


In [ ]:
print(np.hstack((x1,y1)))

[3 6 9 8 4 1 7 5]


In [ ]:
print(np.vstack((x1,y1)))

[[3 6 9 8]
 [4 1 7 5]]


In [ ]:
print(np.dstack((x1,y1)))

[[[3 4]
  [6 1]
  [9 7]
  [8 5]]]


In [ ]:
arr=np.concatenate((x1,y1))
print(np.array_split(arr,4))

[array([3, 6]), array([9, 8]), array([4, 1]), array([7, 5])]
